version: '3.9'

services:
  stargate-app:
    image: node:20-alpine
    working_dir: /app
    container_name: stargate_app_dev
    restart: unless-stopped
    command: sh -c "npm install && npm run dev"
    ports:
      - '5000:5000'
      - '5173:5173'
    environment:
      NODE_ENV: development
      PORT: 5000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: stargate_redis_dev
    restart: unless-stopped
    ports:
      - '6380:6379'
    volumes:
      - redis-data-dev:/data

volumes:
  redis-data-dev:

