version: '3.9'

services:
  stargate-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stargate_app
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: production
      PORT: 5000
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - redis
    command: ['npm', 'run', 'start']

  redis:
    image: redis:7-alpine
    container_name: stargate_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:

